/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.vista;

/**
 *
 * @author ARANDY-PC
 */
public class PanelConvolucion extends javax.swing.JPanel {

    /**
     * Creates new form PanelConvolucion
     */
    public PanelConvolucion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldConvo1 = new javax.swing.JTextField();
        jTextFieldConvo2 = new javax.swing.JTextField();
        jTextFieldConvo3 = new javax.swing.JTextField();
        jTextFieldConvo4 = new javax.swing.JTextField();
        jTextFieldConvo5 = new javax.swing.JTextField();
        jTextFieldConvo6 = new javax.swing.JTextField();
        jTextFieldConvo7 = new javax.swing.JTextField();
        jTextFieldConvo8 = new javax.swing.JTextField();
        jTextFieldConvo9 = new javax.swing.JTextField();
        botonAplicarConvolucionAplicar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("Panel Convolucion");

        jTextFieldConvo1.setText("1");
        jTextFieldConvo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConvo1ActionPerformed(evt);
            }
        });

        jTextFieldConvo2.setText("0");
        jTextFieldConvo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConvo2ActionPerformed(evt);
            }
        });

        jTextFieldConvo3.setText("-1");
        jTextFieldConvo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConvo3ActionPerformed(evt);
            }
        });

        jTextFieldConvo4.setText("1");
        jTextFieldConvo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConvo4ActionPerformed(evt);
            }
        });

        jTextFieldConvo5.setText("0");
        jTextFieldConvo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConvo5ActionPerformed(evt);
            }
        });

        jTextFieldConvo6.setText("-1");
        jTextFieldConvo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConvo6ActionPerformed(evt);
            }
        });

        jTextFieldConvo7.setText("1");
        jTextFieldConvo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConvo7ActionPerformed(evt);
            }
        });

        jTextFieldConvo8.setText("0");
        jTextFieldConvo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConvo8ActionPerformed(evt);
            }
        });

        jTextFieldConvo9.setText("-1");
        jTextFieldConvo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConvo9ActionPerformed(evt);
            }
        });

        botonAplicarConvolucionAplicar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonAplicarConvolucionAplicar.setText("aplicar convolucion");
        botonAplicarConvolucionAplicar.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAplicarConvolucionAplicar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldConvo7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldConvo4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldConvo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldConvo5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldConvo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldConvo8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldConvo6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldConvo9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldConvo3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldConvo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldConvo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldConvo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldConvo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldConvo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldConvo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldConvo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldConvo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldConvo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAplicarConvolucionAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldConvo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConvo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConvo1ActionPerformed

    private void jTextFieldConvo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConvo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConvo2ActionPerformed

    private void jTextFieldConvo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConvo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConvo3ActionPerformed

    private void jTextFieldConvo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConvo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConvo4ActionPerformed

    private void jTextFieldConvo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConvo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConvo5ActionPerformed

    private void jTextFieldConvo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConvo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConvo6ActionPerformed

    private void jTextFieldConvo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConvo7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConvo7ActionPerformed

    private void jTextFieldConvo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConvo8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConvo8ActionPerformed

    private void jTextFieldConvo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConvo9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConvo9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAplicarConvolucionAplicar;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldConvo1;
    public javax.swing.JTextField jTextFieldConvo2;
    public javax.swing.JTextField jTextFieldConvo3;
    public javax.swing.JTextField jTextFieldConvo4;
    public javax.swing.JTextField jTextFieldConvo5;
    public javax.swing.JTextField jTextFieldConvo6;
    public javax.swing.JTextField jTextFieldConvo7;
    public javax.swing.JTextField jTextFieldConvo8;
    public javax.swing.JTextField jTextFieldConvo9;
    // End of variables declaration//GEN-END:variables
}
